
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
      #don't statrt frontend until backend is up and running
    depends_on:
      - backend